name: Actions develop
on:
  push:
    branches:
      # - '*'
      # - '!master'
      # - '!develop'
      - 'feature/**'

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    name: Create branches for Pull Request
    steps:
      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - run: echo "🎉 El evento se ejecutó en la rama ${{ steps.vars.outputs.short_ref }}"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12


      - name: Create Pull Request

        uses: shubhsherl/create-catchup-pr@v0.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{github.repository}}

          SOURCE_BRANCH: "${{ steps.vars.outputs.short_ref }}"
          TARGET_BRANCH: "develop"
          TITLE: '[Pull request - ${{ github.actor }}] Into develop from ${{ steps.vars.outputs.short_ref }}'
          BODY: |
            Update featura
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/InterfazProductosDigitales
# jobs:
#   createBranchPr:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Set output
#         id: vars
#         run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
#       - run: echo "🎉 Esta es la rama de referencia  ${{ steps.vars.outputs.short_ref }}"
#       - uses: actions/checkout@v2
#         with:
#           ref: ${{ steps.vars.outputs.short_ref }}

#       - name: Create Branch
#         uses: peterjgrainger/action-create-branch@v2.0.1
#         env:
#           GITHUB_TOKEN: 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
#         with:
#               branch: 'pr-${{ steps.vars.outputs.short_ref }}'

#       - name: Make changes to pull request
#         run: date +%s > report.txt


#       - name: Create Pull Request
#         id: cpr
#         uses: peter-evans/create-pull-request@v3.10.0
#         with:
#           token: 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
#           base: ${{ steps.vars.outputs.short_ref }}
#           branch: pr-${{ steps.vars.outputs.short_ref }}
#           commit-message: pr - ${{ github.event.head_commit.message }}
#           # committer: GitHub <noreply@github.com>
#           author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
#           signoff: false
#           branch: pr-${{ steps.vars.outputs.short_ref }}
#           base: develop
#           # branch: ${{ steps.vars.outputs.short_ref }}
#           delete-branch: true
#           title: '[Pull request - ${{ github.actor }}] Into develop from ${{ steps.vars.outputs.short_ref }}'
#           body: |
          #   Update featura
          #   - Updated with *today's* date
          #   - Auto-generated by [create-pull-request][1]

          #   [1]: https://github.com/peter-evans/create-pull-request
          # labels: |
          #   feature
          #   automated pr
          # assignees: ${{ github.actor }}
          # # reviewers: ${{ github.actor }}
          # team-reviewers: |
          #   owners
          #   maintainers
          # # milestone: 1
          # draft: false


  # createPullRequest:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set output
  #       id: vars
  #       run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
  #     - uses: actions/checkout@v2
  #     - name: Create Pull Request
  #       id: cpr
  #       uses: peter-evans/create-pull-request@v3.10.0
  #       with:
  #         token: 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
  #         base: develop

  #         branch: pr-${{ steps.vars.outputs.short_ref }}